import cv2
import numpy as np
import argparse
import os
import csv
import time
from tqdm import tqdm
import re


def get_threshold(n):
    if n == 1:
        return 35
    elif n == 2:
        return 85
    elif n == 3:
        return 65
    else:
        return 15


def extract_mask_number(filename):
    match = re.search(r"_mask_(\d+)", filename)
    return int(match.group(1)) if match else -1


def compare_images(_img1, _img2, _threshold, _sizes):

    _img1 = cv2.imread(_img1)
    _img2 = cv2.imread(_img2)

    _img1 = cv2.resize(_img1, dsize=_sizes, interpolation=cv2.INTER_LANCZOS4)
    _img2 = cv2.resize(_img2, dsize=_sizes, interpolation=cv2.INTER_LANCZOS4)

    _img1 = cv2.cvtColor(_img1, cv2.COLOR_BGR2GRAY)
    _img2 = cv2.cvtColor(_img2, cv2.COLOR_BGR2GRAY)

    _, _img1 = cv2.threshold(_img1, 15, 255, cv2.THRESH_BINARY)
    _, _img2 = cv2.threshold(_img2, _threshold, 255, cv2.THRESH_BINARY)

    _error, _diff = mse(_img1, _img2)

    return _error


def mse(i1, i2):
    h, w = i1.shape
    d = cv2.subtract(i1, i2).astype(np.float32)
    err = np.sum(d ** 2)
    MSE = err / (float(h * w))
    return MSE, d


def process_images_1(_model_path, _original_path, _writer, _thr, _sizes):
    sorted_files = sorted(os.listdir(_model_path), key=extract_mask_number)
    for _idf, _model in enumerate(sorted_files):
        print(_model)
        time.sleep(1)
        for _image in tqdm(os.listdir("{}/{}/test_latest/images".format(_model_path, _model)),
                          total=len(os.listdir("{}/{}/test_latest/images".format(_model_path, _model)))):
            if "_real" in _image:
                continue
            try:
                _generated_path = "{}/{}/test_latest/images/{}".format(_model_path, _model, _image)
            except Exception as e:
                print(e)
                continue
            try:
                _mask_image = _image.replace("_fake", f"_mask_{_idf}")
                _reference_path = "{}/{}/{}".format(_original_path,
                                                   _image.replace("_fake", "").replace("_real", "").split('.')[0],
                                                   _mask_image)
                val = compare_images(_reference_path, _generated_path, _thr, _sizes)
                _writer.writerow(
                    [_model, _image.replace("_fake", "").replace("_real", ""), val, f"{float(val / 65025.0):.10f}"])
            except Exception as e:
                print(e)
                continue

def process_images_2(_model_path, _original_path, _writer, _thr, _sizes):
    sorted_files = sorted(os.listdir(_model_path), key=extract_mask_number)
    for _idf, _model in enumerate(sorted_files):
        print(_model)
        time.sleep(1)
        for _image in tqdm(os.listdir("{}/{}/best/label".format(_model_path, _model)),
                          total=len(os.listdir("{}/{}/best/label".format(_model_path, _model)))):
            if "_real" in _image:
                continue
            try:
                _generated_path = "{}/{}/best/label/{}".format(_model_path, _model, _image)
            except Exception as e:
                print(e)
                continue
            try:
                _mask_image = _image.split(".")[0] + f"_mask_{_idf}" + ".png"
                _reference_path = "{}/{}/{}".format(_original_path,
                                                   _image.replace("_fake", "").replace("_real", "").split('.')[0],
                                                   _mask_image)
                val = compare_images(_reference_path, _generated_path, _thr, _sizes)
                _writer.writerow(
                    [_model, _image.replace("_fake", "").replace("_real", ""), val, f"{float(val / 65025.0):.10f}"])
            except Exception as e:
                print(e)
                continue


if __name__ == "__main__":

    parser = argparse.ArgumentParser(description="Run model on input data.")
    parser.add_argument('--path_to_masks', type=str, required=True, help='Path to the folder containing the original masks')
    parser.add_argument('--path_to_model', type=str, required=True, help='Path to the folder containing the masks generated by the specific model')
    parser.add_argument('--model_type', type=int, required=True, help='CycleGAN output: "1", DP-GAN output: "2", OASIS output: "3"')
    parser.add_argument('--output', type=str, required=True, help='Path to the output folder')
    parser.add_argument('--height', type=int, default=1271, help='Original images height')
    parser.add_argument('--width', type=int, default=1005, help='Original images width')

    args = parser.parse_args()

    sizes = (args.width, args.height)

    file_name =  re.split(r"[\\/]", args.path_to_model)
    model_type = int(args.model_type)
    model_path = args.path_to_model
    original_path = args.path_to_masks

    thr = get_threshold(model_type)

    with open(f"{args.output}/{file_name[-1]}.txt", "w", newline='') as f:
        writer = csv.writer(f)
        writer.writerow(["model", "image_name", "MSE", "Normalised MSE <0; 1>"])
        if model_type == 1:
            process_images_1(model_path, original_path, writer, thr, sizes)
        if model_type == 2 or model_type == 3:
            process_images_2(model_path, original_path, writer, thr, sizes)
