import pandas as pd
import numpy as np


if __name__ == "__main__":

    path_to_file = "" # PATH TO FILE GENERATED BY compare_images.py
    df = pd.read_csv(f"{path_to_file}", sep=",")

    binned = pd.cut(df['MSE'], bins=30)
    hist_table = binned.value_counts().sort_index()

    bin_centers = [interval.left + (interval.right - interval.left) / 2 for interval in hist_table.index]

    hist_df = pd.DataFrame({
        'Bin center': bin_centers,
        'Count': hist_table.values
    })

    mu = np.mean(df['MSE'])
    sigma = np.std(df['MSE'])
    print(mu, sigma)

    for idx, row in hist_df.iterrows():
        print(f"({np.round(row['Bin center'], 2)}, {int(row['Count'])}) ", end="")

    print("")
    print([f"{np.round(x, 2) }" for x in list(set(hist_df['Bin center']))])
